// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozxhzgvcalqqrmutikgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96eGh6Z3ZjYWxxcXJtdXRpa2d1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NTIzNTgsImV4cCI6MjA2NTUyODM1OH0.nMAsX4Ai_SmBJOiq89uwwLgpN_f6yBYTtfP5NcUOTtY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);